
package tarearadioboton;

import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author unsis
 */
public class Interfaz extends javax.swing.JFrame {
    
    public Interfaz() {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
        String Descripcion = 
                "Mamífero doméstico de la familia de los cánidos, de\n" +
                "tamaño, forma y pelaje muy  diversos, según las\n" +
                "razas, que tiene olfato muy fino y es inteligente y\n" +
                "muy leal a su dueño.";
        //DESCRIPCIONTextArea.setEditable(false);
        DESCRIPCIONTextArea.append(Descripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        PERRORadioButton = new javax.swing.JRadioButton();
        GATORadioButton = new javax.swing.JRadioButton();
        CABALLORadioButton = new javax.swing.JRadioButton();
        BURRORadioButton = new javax.swing.JRadioButton();
        GALLORadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DESCRIPCIONTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ContenedorImagenJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(PERRORadioButton);
        PERRORadioButton.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        PERRORadioButton.setSelected(true);
        PERRORadioButton.setText("PERRO");
        PERRORadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERRORadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(GATORadioButton);
        GATORadioButton.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        GATORadioButton.setText("GATO");
        GATORadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GATORadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(CABALLORadioButton);
        CABALLORadioButton.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        CABALLORadioButton.setText("CABALLO");
        CABALLORadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CABALLORadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(BURRORadioButton);
        BURRORadioButton.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        BURRORadioButton.setText("BURRO");
        BURRORadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BURRORadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(GALLORadioButton);
        GALLORadioButton.setFont(new java.awt.Font("DejaVu Serif", 1, 14)); // NOI18N
        GALLORadioButton.setText("GALLO");
        GALLORadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GALLORadioButtonActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/boton-de-reproduccion.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        DESCRIPCIONTextArea.setColumns(20);
        DESCRIPCIONTextArea.setRows(5);
        DESCRIPCIONTextArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DESCRIPCIONTextAreaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(DESCRIPCIONTextArea);

        jLabel1.setFont(new java.awt.Font("DejaVu Serif", 2, 24)); // NOI18N
        jLabel1.setText("DESCRIPCIÓN");

        ContenedorImagenJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Perro.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GATORadioButton)
                            .addComponent(CABALLORadioButton)
                            .addComponent(PERRORadioButton)
                            .addComponent(BURRORadioButton)
                            .addComponent(GALLORadioButton))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(ContenedorImagenJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ContenedorImagenJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(PERRORadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GATORadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CABALLORadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BURRORadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GALLORadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        BasicPlayer sonido = new BasicPlayer();
        String ruta = "";        // TODO add your handling code here:
        if(iconn.get){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PERRORadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERRORadioButtonActionPerformed
        ImageIcon icono = new ImageIcon("/home/unsis/NetBeansProjects/TareaRadioBoton/src/IMG/Perro.jpg");
        ContenedorImagenJLabel.setIcon(icono);
        //String Descripcion = "ESTO ES LA DESCRIPCION";
        //DESCRIPCIONTextArea.append(Descripcion);
        String Descripcion =
                "Mamífero doméstico de la familia de los cánidos, de\n" +
                "tamaño, forma y pelaje muy  diversos, según las\n" +
                "razas, que tiene olfato muy fino y es inteligente y\n" +
                "muy leal a su dueño.";
        DESCRIPCIONTextArea.setText("");
        DESCRIPCIONTextArea.setEditable(false);
        DESCRIPCIONTextArea.append(Descripcion);
    }//GEN-LAST:event_PERRORadioButtonActionPerformed

    private void GATORadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GATORadioButtonActionPerformed
        ImageIcon icono = new ImageIcon("/home/unsis/NetBeansProjects/TareaRadioBoton/src/IMG/Gato.jpg");
        ContenedorImagenJLabel.setIcon(icono);
        String Descripcion = 
                "Mamífero de la familia de los félidos, digitígrado, \n" +
                "doméstico, de unos 50 cm de largo desde la cabeza \n" +
                "hasta el arranque de la cola, que por sí sola mide \n" +
                "unos 20 cm, de cabeza redonda, lengua muy áspera,\n" +
                "patas cortas y generalmente pelaje suave y espeso, \n" +
                "de color blanco, gris , pardo , rojizo o negro.";
                
        DESCRIPCIONTextArea.setText("");
        DESCRIPCIONTextArea.setText(Descripcion);
        
    }//GEN-LAST:event_GATORadioButtonActionPerformed

    private void CABALLORadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CABALLORadioButtonActionPerformed
        ImageIcon icono = new ImageIcon("/home/unsis/NetBeansProjects/TareaRadioBoton/src/IMG/Caballo.jpg");
        ContenedorImagenJLabel.setIcon(icono);
        String Descripcion = 
                "Mamífero perisodáctilo domesticado de la familia de\n" +
                "los équidos. Es un herbívoro perisodáctilo de gran\n" +
                "porte, y cuello largo y arqueado poblado por largas\n" +
                "crines.";
                
        DESCRIPCIONTextArea.setText("");
        DESCRIPCIONTextArea.setText(Descripcion);
    }//GEN-LAST:event_CABALLORadioButtonActionPerformed

    private void BURRORadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BURRORadioButtonActionPerformed
        ImageIcon icono = new ImageIcon("/home/unsis/NetBeansProjects/TareaRadioBoton/src/IMG/Burro.jpg");
        ContenedorImagenJLabel.setIcon(icono);
        String Descripcion = 
                "El burro tiene el cuerpo muy bien cubierto de pelo\n" +
                "corto. Posee una crin en la cabeza y cuello. La crin \n" +
                "es corta, delgada y erecta, mientras que la cola es\n" +
                "a manera de mechón.";
                
        DESCRIPCIONTextArea.setText("");
        DESCRIPCIONTextArea.setText(Descripcion);
    }//GEN-LAST:event_BURRORadioButtonActionPerformed

    private void GALLORadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GALLORadioButtonActionPerformed
        ImageIcon icono = new ImageIcon("/home/unsis/NetBeansProjects/TareaRadioBoton/src/IMG/Gallo.jpg");
        ContenedorImagenJLabel.setIcon(icono);
        String Descripcion = 
                "Ave doméstica del orden de las galliformes, con\n" +
                "cresta roja y carnosa, pico corto, grueso y \n" +
                "arqueado, de plumaje abundante, lustroso y a \n" +
                "menudo con visos irisados, cuyo macho tiene tarsos \n" +
                "fuertes armados de espolones, y cuya hembra es de\n" +
                "menor tamaño y tiene la cresta más pequeña.";
        
        DESCRIPCIONTextArea.setText("");
        DESCRIPCIONTextArea.setText(Descripcion);
    }//GEN-LAST:event_GALLORadioButtonActionPerformed

    private void DESCRIPCIONTextAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DESCRIPCIONTextAreaAncestorAdded
            // TODO add your handling code here:
    }//GEN-LAST:event_DESCRIPCIONTextAreaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BURRORadioButton;
    private javax.swing.JRadioButton CABALLORadioButton;
    private javax.swing.JLabel ContenedorImagenJLabel;
    private javax.swing.JTextArea DESCRIPCIONTextArea;
    private javax.swing.JRadioButton GALLORadioButton;
    private javax.swing.JRadioButton GATORadioButton;
    private javax.swing.JRadioButton PERRORadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
